/**  * \brief Gets current Hrm filter coeficients for the provided channels in channelMask. * 
* \pre This function may be called any time after the device has been initialized, and 
* initialization calibrations have taken place *  * \dep_begin * \dep{device->common.devHalInfo} * \dep_end *
 * \param[in,out] device Context variable -Context variable -A pointer to the device settings structure * \param[in] channelMask Channel mask for which channels HRM data are to be retrieved. At least one bit in must be set. * \param[out] txHrmDataArray points to an array of adi_adrvgen6_TxHrmData_t with the number of elements of the array being the number of set bits  *                            in channelMask. The first element in the array is the first bit set, starting from LSB. The size is expected to be  *                            the number of bits High in channelMask, with min size of array being 1, and max being 8. For example, for channelMask *                            equal to 0b01101000, the first element in the array will contain HRM data for Tx3, and the third (and last) will be  *                            relative to Tx6. * \param[in] arrayLength explicit mention of the number of elements in txHrmDataArray. Must match the number of bits set in channelMask. * * \retval adi_adrvgen6_ErrAction_e, ADI_ADRVGEN6_ERR_ACT_NONE if successful */ADI_API adi_adrvgen6_ErrAction_e adi_adrvgen6_TxHrmDataGet(adi_adrvgen6_Device_t* const device,
                                                           const uint8_t channelMask,
                                                           adi_adrvgen6_TxHrmData_t txHrmDataArray[],
                                                           const uint8_t arrayLength);
/**  * \brief Gets current Hrm filter coeficients for the provided channels in channelMask.  *        The user should call this function following an LO reprogram that demands a change in HRM coefficients. * * \pre This function may be called any time after the device has been initialized, and * initialization calibrations have taken place *  * \dep_begin * \dep{device->common.devHalInfo} * \dep_end * * \param[in,out] device Context variable -Context variable -A pointer to the device settings structure * \param[in] channelMask Channel mask for which channels HRM data are to be retrieved. At least one bit in must be set. * \param[in] txHrmDataArray points to an array of adi_adrvgen6_TxHrmData_t with the number of elements of the array being the number of set bits  *                           in channelMask. The first element in the array is the first bit set, starting from LSB. The size is expected to be  *                           the number of bits High in channelMask, with min size of array being 1, and max being 8. For example, for channelMask *                           equal to 0b01101000, the first element in the array will contain HRM data for Tx3, and the third (and last) will be  *                           relative to Tx6. * \param[in] arrayLength explicit mention of the number of elements in txHrmDataArray. Must match the number of bits set in channelMask. * * \retval adi_adrvgen6_ErrAction_e, ADI_ADRVGEN6_ERR_ACT_NONE if successful */ADI_API adi_adrvgen6_ErrAction_e adi_adrvgen6_TxHrmDataSet(adi_adrvgen6_Device_t* const device,
                                                           const uint8_t channelMask,
                                                           const adi_adrvgen6_TxHrmData_t txHrmDataArray[],
                                                           uint8_t arrayLength);